package tela;
import onibus.Onibus;
import javax.swing.ButtonGroup;



/**
 *
 * @author Usuario
 */
public class Tela extends javax.swing.JFrame {
Onibus onibus;

    


    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        onibus= new Onibus();
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        poltrona1 = new javax.swing.JRadioButton();
        poltrona5 = new javax.swing.JRadioButton();
        poltrona9 = new javax.swing.JRadioButton();
        poltrona13 = new javax.swing.JRadioButton();
        poltrona17 = new javax.swing.JRadioButton();
        poltrona21 = new javax.swing.JRadioButton();
        poltrona25 = new javax.swing.JRadioButton();
        poltrona29 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        poltrona30 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        poltrona2 = new javax.swing.JRadioButton();
        poltrona6 = new javax.swing.JRadioButton();
        poltrona10 = new javax.swing.JRadioButton();
        poltrona14 = new javax.swing.JRadioButton();
        poltrona18 = new javax.swing.JRadioButton();
        poltrona22 = new javax.swing.JRadioButton();
        poltrona26 = new javax.swing.JRadioButton();
        poltrona4 = new javax.swing.JRadioButton();
        poltrona27 = new javax.swing.JRadioButton();
        poltrona31 = new javax.swing.JRadioButton();
        poltrona8 = new javax.swing.JRadioButton();
        poltrona12 = new javax.swing.JRadioButton();
        poltrona16 = new javax.swing.JRadioButton();
        poltrona3 = new javax.swing.JRadioButton();
        poltrona20 = new javax.swing.JRadioButton();
        poltrona7 = new javax.swing.JRadioButton();
        poltrona24 = new javax.swing.JRadioButton();
        poltrona11 = new javax.swing.JRadioButton();
        poltrona28 = new javax.swing.JRadioButton();
        poltrona15 = new javax.swing.JRadioButton();
        poltrona32 = new javax.swing.JRadioButton();
        poltrona19 = new javax.swing.JRadioButton();
        poltrona23 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        campoTexto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nomePessoa = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(50, 50, 50, 50));
        setMaximumSize(new java.awt.Dimension(10, 10));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setName("onibus"); // NOI18N

        poltrona1.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona1.setForeground(new java.awt.Color(0, 102, 102));
        poltrona1.setText("01");
        poltrona1.setToolTipText("");
        poltrona1.setAlignmentX(10.0F);
        poltrona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona1ActionPerformed(evt);
            }
        });

        poltrona5.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona5.setForeground(new java.awt.Color(0, 102, 102));
        poltrona5.setText("05");
        poltrona5.setToolTipText("");
        poltrona5.setAlignmentX(10.0F);
        poltrona5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona5ActionPerformed(evt);
            }
        });

        poltrona9.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona9.setForeground(new java.awt.Color(0, 102, 102));
        poltrona9.setText("09");
        poltrona9.setToolTipText("");
        poltrona9.setAlignmentX(10.0F);
        poltrona9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona9ActionPerformed(evt);
            }
        });

        poltrona13.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona13.setForeground(new java.awt.Color(0, 102, 102));
        poltrona13.setText("13");
        poltrona13.setToolTipText("");
        poltrona13.setAlignmentX(10.0F);
        poltrona13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona13ActionPerformed(evt);
            }
        });

        poltrona17.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona17.setForeground(new java.awt.Color(0, 102, 102));
        poltrona17.setText("17");
        poltrona17.setToolTipText("");
        poltrona17.setAlignmentX(10.0F);
        poltrona17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona17ActionPerformed(evt);
            }
        });

        poltrona21.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona21.setForeground(new java.awt.Color(0, 102, 102));
        poltrona21.setText("21");
        poltrona21.setToolTipText("");
        poltrona21.setAlignmentX(10.0F);
        poltrona21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona21ActionPerformed(evt);
            }
        });

        poltrona25.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona25.setForeground(new java.awt.Color(0, 102, 102));
        poltrona25.setText("25");
        poltrona25.setToolTipText("");
        poltrona25.setAlignmentX(10.0F);
        poltrona25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona25ActionPerformed(evt);
            }
        });

        poltrona29.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona29.setForeground(new java.awt.Color(0, 102, 102));
        poltrona29.setText("29");
        poltrona29.setToolTipText("");
        poltrona29.setAlignmentX(10.0F);
        poltrona29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona29ActionPerformed(evt);
            }
        });

        jRadioButton9.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(0, 102, 102));
        jRadioButton9.setText("32");
        jRadioButton9.setToolTipText("");
        jRadioButton9.setAlignmentX(10.0F);
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        poltrona30.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona30.setForeground(new java.awt.Color(0, 102, 102));
        poltrona30.setText("30");
        poltrona30.setToolTipText("");
        poltrona30.setAlignmentX(10.0F);
        poltrona30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona30ActionPerformed(evt);
            }
        });

        jRadioButton13.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jRadioButton13.setForeground(new java.awt.Color(0, 102, 102));
        jRadioButton13.setText("33");
        jRadioButton13.setToolTipText("");
        jRadioButton13.setAlignmentX(10.0F);
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        poltrona2.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona2.setForeground(new java.awt.Color(0, 102, 102));
        poltrona2.setText("02");
        poltrona2.setToolTipText("");
        poltrona2.setAlignmentX(10.0F);
        poltrona2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona2ActionPerformed(evt);
            }
        });

        poltrona6.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona6.setForeground(new java.awt.Color(0, 102, 102));
        poltrona6.setText("06");
        poltrona6.setToolTipText("");
        poltrona6.setAlignmentX(10.0F);
        poltrona6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona6ActionPerformed(evt);
            }
        });

        poltrona10.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona10.setForeground(new java.awt.Color(0, 102, 102));
        poltrona10.setText("10");
        poltrona10.setToolTipText("");
        poltrona10.setAlignmentX(10.0F);
        poltrona10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona10ActionPerformed(evt);
            }
        });

        poltrona14.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona14.setForeground(new java.awt.Color(0, 102, 102));
        poltrona14.setText("14");
        poltrona14.setToolTipText("");
        poltrona14.setAlignmentX(10.0F);
        poltrona14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona14ActionPerformed(evt);
            }
        });

        poltrona18.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona18.setForeground(new java.awt.Color(0, 102, 102));
        poltrona18.setText("18");
        poltrona18.setToolTipText("");
        poltrona18.setAlignmentX(10.0F);
        poltrona18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona18ActionPerformed(evt);
            }
        });

        poltrona22.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona22.setForeground(new java.awt.Color(0, 102, 102));
        poltrona22.setText("22");
        poltrona22.setToolTipText("");
        poltrona22.setAlignmentX(10.0F);
        poltrona22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona22ActionPerformed(evt);
            }
        });

        poltrona26.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona26.setForeground(new java.awt.Color(0, 102, 102));
        poltrona26.setText("26");
        poltrona26.setToolTipText("");
        poltrona26.setAlignmentX(10.0F);
        poltrona26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona26ActionPerformed(evt);
            }
        });

        poltrona4.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona4.setForeground(new java.awt.Color(0, 102, 102));
        poltrona4.setText("04");
        poltrona4.setToolTipText("");
        poltrona4.setAlignmentX(10.0F);
        poltrona4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona4ActionPerformed(evt);
            }
        });

        poltrona27.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona27.setForeground(new java.awt.Color(0, 102, 102));
        poltrona27.setText("19");
        poltrona27.setToolTipText("");
        poltrona27.setAlignmentX(10.0F);
        poltrona27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona27ActionPerformed(evt);
            }
        });

        poltrona31.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona31.setForeground(new java.awt.Color(0, 102, 102));
        poltrona31.setText("30");
        poltrona31.setToolTipText("");
        poltrona31.setAlignmentX(10.0F);
        poltrona31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona31ActionPerformed(evt);
            }
        });

        poltrona8.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona8.setForeground(new java.awt.Color(0, 102, 102));
        poltrona8.setText("12");
        poltrona8.setToolTipText("");
        poltrona8.setAlignmentX(10.0F);
        poltrona8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona8ActionPerformed(evt);
            }
        });

        poltrona12.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona12.setForeground(new java.awt.Color(0, 102, 102));
        poltrona12.setText("16");
        poltrona12.setToolTipText("");
        poltrona12.setAlignmentX(10.0F);
        poltrona12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona12ActionPerformed(evt);
            }
        });

        poltrona16.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona16.setForeground(new java.awt.Color(0, 102, 102));
        poltrona16.setText("20");
        poltrona16.setToolTipText("");
        poltrona16.setAlignmentX(10.0F);
        poltrona16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona16ActionPerformed(evt);
            }
        });

        poltrona3.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona3.setForeground(new java.awt.Color(0, 102, 102));
        poltrona3.setText("03");
        poltrona3.setToolTipText("");
        poltrona3.setAlignmentX(10.0F);
        poltrona3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona3ActionPerformed(evt);
            }
        });

        poltrona20.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona20.setForeground(new java.awt.Color(0, 102, 102));
        poltrona20.setText("28");
        poltrona20.setToolTipText("");
        poltrona20.setActionCommand("28");
        poltrona20.setAlignmentX(10.0F);
        poltrona20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona20ActionPerformed(evt);
            }
        });

        poltrona7.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona7.setForeground(new java.awt.Color(0, 102, 102));
        poltrona7.setText("11");
        poltrona7.setToolTipText("");
        poltrona7.setAlignmentX(10.0F);
        poltrona7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona7ActionPerformed(evt);
            }
        });

        poltrona24.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona24.setForeground(new java.awt.Color(0, 102, 102));
        poltrona24.setText("08");
        poltrona24.setToolTipText("");
        poltrona24.setAlignmentX(10.0F);
        poltrona24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona24ActionPerformed(evt);
            }
        });

        poltrona11.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona11.setForeground(new java.awt.Color(0, 102, 102));
        poltrona11.setText("15");
        poltrona11.setToolTipText("");
        poltrona11.setAlignmentX(10.0F);
        poltrona11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona11ActionPerformed(evt);
            }
        });

        poltrona28.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona28.setForeground(new java.awt.Color(0, 102, 102));
        poltrona28.setText("24");
        poltrona28.setToolTipText("");
        poltrona28.setAlignmentX(10.0F);
        poltrona28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona28ActionPerformed(evt);
            }
        });

        poltrona15.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona15.setForeground(new java.awt.Color(0, 102, 102));
        poltrona15.setText("23");
        poltrona15.setToolTipText("");
        poltrona15.setAlignmentX(10.0F);
        poltrona15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona15ActionPerformed(evt);
            }
        });

        poltrona32.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona32.setForeground(new java.awt.Color(0, 102, 102));
        poltrona32.setText("31");
        poltrona32.setToolTipText("");
        poltrona32.setAlignmentX(10.0F);
        poltrona32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona32ActionPerformed(evt);
            }
        });

        poltrona19.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona19.setForeground(new java.awt.Color(0, 102, 102));
        poltrona19.setText("27");
        poltrona19.setToolTipText("");
        poltrona19.setActionCommand("");
        poltrona19.setAlignmentX(10.0F);
        poltrona19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona19ActionPerformed(evt);
            }
        });

        poltrona23.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        poltrona23.setForeground(new java.awt.Color(0, 102, 102));
        poltrona23.setText("07");
        poltrona23.setToolTipText("");
        poltrona23.setAlignmentX(10.0F);
        poltrona23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona23ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Insira seu nome");

        campoTexto.setForeground(new java.awt.Color(0, 102, 102));
        campoTexto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoTexto.setText("Nenhuma poltrona selecionada");
        campoTexto.setToolTipText("");
        campoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/onibus2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(500, 352));
        jLabel2.setMinimumSize(new java.awt.Dimension(500, 352));
        jLabel2.setPreferredSize(new java.awt.Dimension(500, 352));
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Selecione sua poltrona");

        nomePessoa.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        nomePessoa.setForeground(new java.awt.Color(0, 102, 102));

        campoNome.setForeground(new java.awt.Color(0, 102, 102));
        campoNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoNome.setToolTipText("");
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(poltrona29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                            .addComponent(poltrona25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(poltrona21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(poltrona17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(poltrona13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(poltrona9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(poltrona30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                            .addComponent(poltrona10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(poltrona18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(poltrona22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(poltrona26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(poltrona14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(poltrona1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(poltrona5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(poltrona6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(poltrona2, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(poltrona27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(poltrona31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(poltrona3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(poltrona7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(poltrona11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(poltrona15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(poltrona19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(poltrona23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(poltrona4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(poltrona8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(poltrona12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(poltrona16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(poltrona20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(poltrona24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(poltrona28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(poltrona32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(poltrona1)
                                    .addComponent(poltrona2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(poltrona5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(poltrona6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(poltrona4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(poltrona3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(poltrona24, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(poltrona23, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(poltrona9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(poltrona10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(poltrona14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(poltrona13)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(poltrona7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(poltrona8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(poltrona12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(poltrona11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(poltrona18, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poltrona17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poltrona27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(poltrona16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poltrona15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(poltrona22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(poltrona21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(poltrona28))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(poltrona19, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(poltrona25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(poltrona26))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(poltrona20, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(5, 5, 5)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(poltrona30, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(poltrona29, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(poltrona32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(poltrona31, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22)
                        .addComponent(nomePessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(520, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
      String a= "";
 
    private void atualizarTela(){
        if (onibus.isOcupado()){
            this.campoTexto.setText(a);
        }
     
    }    
    private void poltrona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona1ActionPerformed
        onibus.ocupar(); 
        a="Poltrona 1 ocupada";             
        this.atualizarTela();
         
    }//GEN-LAST:event_poltrona1ActionPerformed

    private void poltrona2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona2ActionPerformed
        onibus.ocupar();
        a="Poltrona 2 ocupada";             
        this.atualizarTela();
    }//GEN-LAST:event_poltrona2ActionPerformed

    private void poltrona3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona3ActionPerformed
        onibus.ocupar();
        a="Poltrona 3 ocupada";             
        this.atualizarTela();
    }//GEN-LAST:event_poltrona3ActionPerformed

    private void poltrona4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona4ActionPerformed
         onibus.ocupar();
         a="Poltrona 4 ocupada";             
          this.atualizarTela();
    }//GEN-LAST:event_poltrona4ActionPerformed

    private void poltrona5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona5ActionPerformed
         onibus.ocupar();
         a="Poltrona 5 ocupada";             
          this.atualizarTela();
    }//GEN-LAST:event_poltrona5ActionPerformed

    private void poltrona6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona6ActionPerformed
        onibus.ocupar();
        a="Poltrona 6 ocupada";             
         this.atualizarTela();
    }//GEN-LAST:event_poltrona6ActionPerformed

    private void poltrona7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona7ActionPerformed
        onibus.ocupar();
        a="Poltrona 7 ocupada";             
         this.atualizarTela();
    }//GEN-LAST:event_poltrona7ActionPerformed

    private void poltrona8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona8ActionPerformed
        onibus.ocupar();
        a="Poltrona 8 ocupada";             
         this.atualizarTela();
    }//GEN-LAST:event_poltrona8ActionPerformed

    private void poltrona9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona9ActionPerformed
         onibus.ocupar(); 
         a="Poltrona 9 ocupada";             
         this.atualizarTela();
    }//GEN-LAST:event_poltrona9ActionPerformed

    private void poltrona10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona10ActionPerformed
         onibus.ocupar();
         a="Poltrona 10 ocupada";             
          this.atualizarTela();
    }//GEN-LAST:event_poltrona10ActionPerformed

    private void poltrona11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona11ActionPerformed
        onibus.ocupar();
        a="Poltrona 11 ocupada";             
         this.atualizarTela();
    }//GEN-LAST:event_poltrona11ActionPerformed

    private void poltrona12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona12ActionPerformed
        onibus.ocupar();
        a="Poltrona 12 ocupada";             
         this.atualizarTela();
         
    }//GEN-LAST:event_poltrona12ActionPerformed

    private void poltrona13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona13ActionPerformed
         onibus.ocupar();
         a="Poltrona 13 ocupada";             
          this.atualizarTela();
    }//GEN-LAST:event_poltrona13ActionPerformed

    private void poltrona14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona14ActionPerformed
         onibus.ocupar();
         a="Poltrona 14 ocupada";             
          this.atualizarTela();
         
    }//GEN-LAST:event_poltrona14ActionPerformed

    private void poltrona15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona15ActionPerformed
       onibus.ocupar();
       a="Poltrona 15 ocupada";             
        this.atualizarTela();
    }//GEN-LAST:event_poltrona15ActionPerformed

    private void poltrona16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona16ActionPerformed
        onibus.ocupar();
        a="Poltrona 16 ocupada";             
         this.atualizarTela();
    }//GEN-LAST:event_poltrona16ActionPerformed

    private void poltrona17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona17ActionPerformed
        onibus.ocupar();
        a="Poltrona 17 ocupada";             
         this.atualizarTela();
    }//GEN-LAST:event_poltrona17ActionPerformed

    private void poltrona18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona18ActionPerformed
        onibus.ocupar();
        a="Poltrona 18 ocupada";             
         this.atualizarTela();
    }//GEN-LAST:event_poltrona18ActionPerformed

    private void poltrona19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona19ActionPerformed
         onibus.ocupar();
         a="Poltrona 19 ocupada";             
          this.atualizarTela();
    }//GEN-LAST:event_poltrona19ActionPerformed

    private void poltrona20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona20ActionPerformed
         onibus.ocupar();
         a="Poltrona 20 ocupada";             
          this.atualizarTela();
    }//GEN-LAST:event_poltrona20ActionPerformed

    private void poltrona21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona21ActionPerformed
         onibus.ocupar();
         a="Poltrona 21 ocupada";             
          this.atualizarTela();
    }//GEN-LAST:event_poltrona21ActionPerformed

    private void poltrona22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona22ActionPerformed
         onibus.ocupar();
         a="Poltrona 22 ocupada";             
          this.atualizarTela();
    }//GEN-LAST:event_poltrona22ActionPerformed

    private void poltrona23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona23ActionPerformed
        onibus.ocupar();
        a="Poltrona 23 ocupada";             
         this.atualizarTela();
    }//GEN-LAST:event_poltrona23ActionPerformed

    private void poltrona24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona24ActionPerformed
       onibus.ocupar();
       a="Poltrona 24 ocupada";             
        this.atualizarTela();
    }//GEN-LAST:event_poltrona24ActionPerformed

    private void poltrona25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona25ActionPerformed
         onibus.ocupar();
         a="Poltrona 25 ocupada";             
          this.atualizarTela();
    }//GEN-LAST:event_poltrona25ActionPerformed

    private void poltrona26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona26ActionPerformed
        onibus.ocupar();
        a="Poltrona 26 ocupada";             
         this.atualizarTela();
    }//GEN-LAST:event_poltrona26ActionPerformed

    private void poltrona27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona27ActionPerformed
         onibus.ocupar();
         a="Poltrona 27 ocupada";             
          this.atualizarTela();
    }//GEN-LAST:event_poltrona27ActionPerformed

    private void poltrona28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona28ActionPerformed
        onibus.ocupar();
        a="Poltrona 28 ocupada";             
         this.atualizarTela();
    }//GEN-LAST:event_poltrona28ActionPerformed

    private void poltrona29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona29ActionPerformed
         onibus.ocupar();
         a="Poltrona 29 ocupada";             
          this.atualizarTela();
    }//GEN-LAST:event_poltrona29ActionPerformed

    private void poltrona30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona30ActionPerformed
         onibus.ocupar();
         a="Poltrona 30 ocupada";             
          this.atualizarTela();
    }//GEN-LAST:event_poltrona30ActionPerformed

    private void poltrona31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona31ActionPerformed
        onibus.ocupar();
        a="Poltrona 31 ocupada";             
         this.atualizarTela();
    }//GEN-LAST:event_poltrona31ActionPerformed

    private void poltrona32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona32ActionPerformed
        onibus.ocupar();
        a="Poltrona 32 ocupada";             
         this.atualizarTela();
    }//GEN-LAST:event_poltrona32ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
         onibus.ocupar();
         a="Poltrona 33 ocupada";             
          this.atualizarTela();
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        onibus.ocupar();
         this.atualizarTela();
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void campoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
   
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nomePessoa;
    private javax.swing.JRadioButton poltrona1;
    private javax.swing.JRadioButton poltrona10;
    private javax.swing.JRadioButton poltrona11;
    private javax.swing.JRadioButton poltrona12;
    private javax.swing.JRadioButton poltrona13;
    private javax.swing.JRadioButton poltrona14;
    private javax.swing.JRadioButton poltrona15;
    private javax.swing.JRadioButton poltrona16;
    private javax.swing.JRadioButton poltrona17;
    private javax.swing.JRadioButton poltrona18;
    private javax.swing.JRadioButton poltrona19;
    private javax.swing.JRadioButton poltrona2;
    private javax.swing.JRadioButton poltrona20;
    private javax.swing.JRadioButton poltrona21;
    private javax.swing.JRadioButton poltrona22;
    private javax.swing.JRadioButton poltrona23;
    private javax.swing.JRadioButton poltrona24;
    private javax.swing.JRadioButton poltrona25;
    private javax.swing.JRadioButton poltrona26;
    private javax.swing.JRadioButton poltrona27;
    private javax.swing.JRadioButton poltrona28;
    private javax.swing.JRadioButton poltrona29;
    private javax.swing.JRadioButton poltrona3;
    private javax.swing.JRadioButton poltrona30;
    private javax.swing.JRadioButton poltrona31;
    private javax.swing.JRadioButton poltrona32;
    private javax.swing.JRadioButton poltrona4;
    private javax.swing.JRadioButton poltrona5;
    private javax.swing.JRadioButton poltrona6;
    private javax.swing.JRadioButton poltrona7;
    private javax.swing.JRadioButton poltrona8;
    private javax.swing.JRadioButton poltrona9;
    // End of variables declaration//GEN-END:variables
}
